name: "go-aio"
description: "Setup go with auth and vendor"

inputs:
  user:
    description: "User to authenticate against"
    required: true
    default: ""
  pat:
    description: "PAT token to authenticate against"
    required: true
    default: ""
  version:
    description: "Go version"
    required: false
    default: ""
  version-file:
    description: "Go version file (go.mod)"
    required: false
    default: "go.mod"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.version }}
        go-version-file: ${{ inputs.version-file }}
        architecture: x64
        cache: true
    - run: git config --global url.https://${{ inputs.user }}:${{ inputs.pat }}@github.com/.insteadOf https://github.com/
      shell: bash
    - run: go mod vendor
      shell: bash
